export const INITIAL_VALUES = {
  id: undefined,
  fullName: undefined,
  birthdate: undefined,
  city: undefined,
  nationalIdNumber: undefined,
  // studyType: undefined,
  qualificationClass: undefined,
  specialization: undefined,
  educationalInstitute: undefined,
  gpa: undefined,
  gpaMax: undefined,
  hasTakenQiyas: undefined,
  qiyasScore: undefined,
  qiyasSubjectScore: undefined,
  email: undefined,
  graduationDate: undefined,
  phoneNumber: undefined,
}
